import Navbar from "./ui/navbar/navbar";
import Footer from "./ui/footer/footer";
import type { Metadata } from "next";
// import favicon from "../public/favicon_io";
import {
  Geist,
  Geist_Mono,
  Ibarra_Real_Nova,
  Public_Sans,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// My fonts
const ibarra_real_nova = Ibarra_Real_Nova({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

const public_sans = Public_Sans({
  weight: "300",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="../public/favicon_io/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="../public/favicon_io/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="../public/favicon_io/favicon-16x16.png"
        />
        <link rel="manifest" href="../public/favicon_io/site.webmanifest" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ibarra_real_nova.className} ${public_sans.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
